"""`docs/CREDITS.md`: the published manifest's credits, audio stems and event citations as a
Markdown page, so the repository carries the same attributions the in-app credits panel shows.
Rendered from the `Manifest` alone and rewritten on every `earthlapse publish`, so it cannot
drift from what the site ships."""

import math
from pathlib import Path

from pipeline.manifest import Manifest, TimelineEvent
from pipeline.shapes import GeoTime

CREDITS_DOC = Path("docs") / "CREDITS.md"

# The calendar year t = 0 stands for (web/src/timeline/epoch.ts PRESENT_CE_YEAR).
PRESENT_CE_YEAR = 2025
# Below this age an event reads better as a calendar year than in ka.
CALENDAR_AGE_LIMIT = 12_000


def _trimmed(value: float, decimals: int) -> str:
    return f"{value:,.{decimals}f}".rstrip("0").rstrip(".")


def format_when(t: GeoTime) -> str:
    if t >= 1e9:
        return f"{_trimmed(t / 1e9, 2)} Ga"
    if t >= 1e6:
        return f"{_trimmed(t / 1e6, 1)} Ma"
    if t >= CALENDAR_AGE_LIMIT:
        return f"{_trimmed(t / 1e3, 1)} ka"
    # The calendar year the instant falls in; year 0 does not exist, so 0 is 1 BCE.
    year = math.floor(PRESENT_CE_YEAR - t)
    return f"{year} CE" if year > 0 else f"{1 - year} BCE"


def _placement(event: TimelineEvent) -> GeoTime:
    return event.t if event.t is not None else (event.t_min + event.t_max) / 2


def _event_when(event: TimelineEvent) -> str:
    if event.t is not None or event.t_min == event.t_max:
        return format_when(_placement(event))
    return f"{format_when(event.t_max)} – {format_when(event.t_min)}"


def _cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def _link(label: str, url: str) -> str:
    return f"[{label}]({url})" if url else label


def render_credits(manifest: Manifest) -> str:
    lines = [
        "# Credits and sources",
        "",
        "Generated by `earthlapse publish` from the published manifest: the same attributions the",
        "site's *About & credits* panel shows. Do not edit by hand.",
        "",
        "Scene images are AI-generated reconstructions written from the research cited in",
        "`data/scenes.yaml`; they are illustrations, not data.",
        "",
        "## Datasets",
        "",
    ]
    for credit in sorted(manifest.credits, key=lambda c: c.title.casefold()):
        lines += [
            f"### {_link(credit.title, credit.url)}",
            "",
            f"{_cell(credit.citation)}",
            "",
            f"**Licence:** {_cell(credit.licence)}",
            "",
            f"Source directory: [`sources/{credit.source_id}/`](../sources/{credit.source_id}/)",
            "",
        ]
    if manifest.audio_stems:
        lines += ["## Ambient sound", "", "| Recording | Author | Licence |", "|---|---|---|"]
        lines += [
            f"| {_link(_cell(stem.title), stem.source_url)} | {_cell(stem.author)} "
            f"| {_cell(stem.licence)} |"
            for stem in sorted(manifest.audio_stems, key=lambda s: s.title.casefold())
        ]
        lines.append("")
    if manifest.events:
        lines += ["## Events", "", "| When | Event | Source |", "|---|---|---|"]
        lines += [
            f"| {_event_when(event)} | {_cell(event.label)} | {_cell(event.citation)} |"
            for event in sorted(manifest.events, key=_placement, reverse=True)
        ]
        lines.append("")
    return "\n".join(lines)


def write_credits(manifest: Manifest, root: Path) -> Path:
    path = root / CREDITS_DOC
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_credits(manifest))
    return path
